#!/usr/bin/env bash
# Command to make an nginx server listen on port 80

# remove the default Nginx configuration filr
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
